services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
      - PHP_CS_FIXER_IGNORE_ENV=true
    command:  ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html/routes/"]
